<?php
declare(strict_types=1);

use Yiyunying\Controllers\Admin\AppController as AdminApp;
use Yiyunying\Controllers\Admin\ActivityController as AdminActivity;
use Yiyunying\Controllers\Admin\AuthController as AdminAuth;
use Yiyunying\Controllers\Admin\BillingController as AdminBilling;
use Yiyunying\Controllers\Admin\BountyController as AdminBounty;
use Yiyunying\Controllers\Admin\CardController as AdminCard;
use Yiyunying\Controllers\Admin\CommerceController as AdminCommerce;
use Yiyunying\Controllers\Admin\CommunicationController as AdminCommunication;
use Yiyunying\Controllers\Admin\CommunityController as AdminCommunity;
use Yiyunying\Controllers\Admin\ContentController as AdminContent;
use Yiyunying\Controllers\Admin\ContentModerationController as AdminContentModeration;
use Yiyunying\Controllers\Admin\DocumentController as AdminDocument;
use Yiyunying\Controllers\Admin\ExchangeController as AdminExchange;
use Yiyunying\Controllers\Admin\FileFeedbackController as AdminFileFeedback;
use Yiyunying\Controllers\Admin\ForumController as AdminForum;
use Yiyunying\Controllers\Admin\ForumStructureController as AdminForumStructure;
use Yiyunying\Controllers\Admin\GroupController as AdminGroup;
use Yiyunying\Controllers\Admin\IdentityController as AdminIdentity;
use Yiyunying\Controllers\Admin\AiKnowledgeController as AdminAiKnowledge;
use Yiyunying\Controllers\Admin\LifecycleController as AdminLifecycle;
use Yiyunying\Controllers\Admin\PollController as AdminPoll;
use Yiyunying\Controllers\Admin\ResourceController as AdminResource;
use Yiyunying\Controllers\Admin\RewardController as AdminReward;
use Yiyunying\Controllers\Admin\SocialController as AdminSocial;
use Yiyunying\Controllers\Admin\StatisticsController as AdminStatistics;
use Yiyunying\Controllers\Admin\UserController as AdminUser;
use Yiyunying\Controllers\Platform\AdminController as PlatformAdmin;
use Yiyunying\Controllers\Platform\AiKnowledgeController as PlatformAiKnowledge;
use Yiyunying\Controllers\Platform\ActivityController as PlatformActivity;
use Yiyunying\Controllers\Platform\AuthController as PlatformAuth;
use Yiyunying\Controllers\Platform\BillingController as PlatformBilling;
use Yiyunying\Controllers\Platform\DashboardController as PlatformDashboard;
use Yiyunying\Controllers\Platform\DataConsoleController as PlatformDataConsole;
use Yiyunying\Controllers\Platform\CommunityController as PlatformCommunity;
use Yiyunying\Controllers\Platform\ExchangeController as PlatformExchange;
use Yiyunying\Controllers\Platform\GovernanceController as PlatformGovernance;
use Yiyunying\Controllers\Platform\LifecycleController as PlatformLifecycle;
use Yiyunying\Controllers\Platform\IdentityController as PlatformIdentity;
use Yiyunying\Controllers\Platform\PollController as PlatformPoll;
use Yiyunying\Controllers\Platform\OperatorController as PlatformOperator;
use Yiyunying\Controllers\Platform\OversightController as PlatformOversight;
use Yiyunying\Controllers\Platform\RewardController as PlatformReward;
use Yiyunying\Controllers\PublicApi\BootstrapController as PublicBootstrap;
use Yiyunying\Controllers\PublicApi\CaptchaController as PublicCaptcha;
use Yiyunying\Controllers\PublicApi\FileController as PublicFile;
use Yiyunying\Controllers\PublicApi\ForumController as PublicForum;
use Yiyunying\Controllers\PublicApi\ForumMediaController as PublicForumMedia;
use Yiyunying\Controllers\PublicApi\HealthController;
use Yiyunying\Controllers\PublicApi\LifecycleController as PublicLifecycle;
use Yiyunying\Controllers\PublicApi\PaymentController as PublicPayment;
use Yiyunying\Controllers\PublicApi\ResourceController as PublicResource;
use Yiyunying\Controllers\PublicApi\VerificationController as PublicVerification;
use Yiyunying\Controllers\User\AuthController as UserAuth;
use Yiyunying\Controllers\User\AiConversationController as UserAiConversation;
use Yiyunying\Controllers\User\ActivityController as UserActivity;
use Yiyunying\Controllers\User\CardController as UserCard;
use Yiyunying\Controllers\User\CloudSyncController as UserCloudSync;
use Yiyunying\Controllers\User\BountyController as UserBounty;
use Yiyunying\Controllers\User\CommerceController as UserCommerce;
use Yiyunying\Controllers\User\CommunicationController as UserCommunication;
use Yiyunying\Controllers\User\DocumentController as UserDocument;
use Yiyunying\Controllers\User\FileFeedbackController as UserFileFeedback;
use Yiyunying\Controllers\User\FavoriteController as UserFavorite;
use Yiyunying\Controllers\User\ForumController as UserForum;
use Yiyunying\Controllers\User\ForumStructureController as UserForumStructure;
use Yiyunying\Controllers\User\GroupController as UserGroup;
use Yiyunying\Controllers\User\IdentityController as UserIdentity;
use Yiyunying\Controllers\User\MomentController as UserMoment;
use Yiyunying\Controllers\User\NoticeController as UserNotice;
use Yiyunying\Controllers\User\PollController as UserPoll;
use Yiyunying\Controllers\User\ResourceController as UserResource;
use Yiyunying\Controllers\User\RewardController as UserReward;
use Yiyunying\Controllers\User\SocialController as UserSocial;
use Yiyunying\Controllers\User\ShopController as UserShop;
use Yiyunying\Controllers\User\SpeechController as UserSpeech;
use Yiyunying\Controllers\User\StickerController as UserSticker;
use Yiyunying\Controllers\User\VoiceCallController as UserVoiceCall;
use Yiyunying\Core\Router;

$router = new Router();

// Health and public application bootstrap.
$router->get('/', [HealthController::class, 'show']);
$router->get('/api/health', [HealthController::class, 'show']);
$router->get('/api/public/app', [PublicBootstrap::class, 'app']);
$router->get('/api/public/bootstrap', [PublicBootstrap::class, 'bootstrap']);
$router->get('/api/public/features', [PublicBootstrap::class, 'features']);
$router->get('/api/public/notices', [PublicBootstrap::class, 'notices']);
$router->get('/api/public/banners', [PublicBootstrap::class, 'banners']);
$router->get('/api/public/version', [PublicBootstrap::class, 'version']);
$router->post('/api/public/app/visit', [PublicBootstrap::class, 'recordVisit']);
$router->get('/api/public/app/statistics', [PublicBootstrap::class, 'statistics']);
$router->post('/api/public/card-login', [UserCard::class, 'login']);
$router->post('/api/public/card-auto-login', [UserCard::class, 'autoLogin']);
$router->get('/api/public/lifecycle', [PublicLifecycle::class, 'check']);
$router->get('/api/public/note-shares/{share_code}', [PublicBootstrap::class, 'documentShare']);
$router->get('/api/public/resource-categories', [PublicResource::class, 'categories']);
$router->get('/api/public/resources', [PublicResource::class, 'resources']);
$router->get('/api/public/resources/{resource_id}', [PublicResource::class, 'show']);
$router->get('/api/public/forum-plates', [PublicForum::class, 'plates']);
$router->get('/api/public/forum-posts', [PublicForum::class, 'posts']);
$router->get('/api/public/forum-posts/{post_id}', [PublicForum::class, 'show']);
$router->get('/api/public/forum-media/{attachment_id}', [PublicForumMedia::class, 'show']);
$router->get('/api/public/remote-files/{file_id}', [PublicFile::class, 'show']);
$router->post('/api/public/captcha', [PublicCaptcha::class, 'create']);
$router->post('/api/public/verification-code/email', [PublicVerification::class, 'email']);
$router->post('/api/public/payment/callback/{channel}', [PublicPayment::class, 'callback']);

// Level 1 platform owner and level 2 authorized-platform accounts.
$router->post('/api/platform/login', [PlatformAuth::class, 'login']);
$router->post('/api/platform/logout', [PlatformAuth::class, 'logout']);
$router->get('/api/platform/me', [PlatformAuth::class, 'me']);
$router->get('/api/platform/permissions', [PlatformAuth::class, 'permissions']);
$router->put('/api/platform/profile', [PlatformAuth::class, 'profile']);
$router->post('/api/platform/profile/avatar', [PlatformAuth::class, 'avatar']);
$router->put('/api/platform/password', [PlatformAuth::class, 'password']);
$router->get('/api/platform/login-logs', [PlatformAuth::class, 'loginLogs']);
$router->get('/api/platform/identity-unbind-requests', [PlatformIdentity::class, 'index']);
$router->post('/api/platform/identity-unbind-requests/{request_id}/review', [PlatformIdentity::class, 'review']);
$router->get('/api/platform/my-identity-unbind-requests', [PlatformIdentity::class, 'mine']);
$router->post('/api/platform/my-identity-unbind-requests', [PlatformIdentity::class, 'requestMine']);
$router->get('/api/platform/dashboard', [PlatformDashboard::class, 'dashboard']);
$router->get('/api/platform/settings', [PlatformDashboard::class, 'settings']);
$router->put('/api/platform/settings', [PlatformDashboard::class, 'saveSettings']);
$router->get('/api/platform/ip-statistics', [PlatformDashboard::class, 'ipStatistics']);
$router->get('/api/platform/admin-registration-logs', [PlatformDashboard::class, 'registrationLogs']);
$router->get('/api/platform/admin-login-logs', [PlatformDashboard::class, 'adminLoginLogs']);
$router->get('/api/platform/operation-logs', [PlatformDashboard::class, 'operationLogs']);
$router->get('/api/platform/data-console/tables', [PlatformDataConsole::class, 'tables']);
$router->get('/api/platform/data-console/{table}', [PlatformDataConsole::class, 'rows']);
$router->post('/api/platform/data-console/{table}', [PlatformDataConsole::class, 'create']);
$router->put('/api/platform/data-console/{table}/{row_id}', [PlatformDataConsole::class, 'update']);
$router->delete('/api/platform/data-console/{table}/{row_id}', [PlatformDataConsole::class, 'delete']);
$router->get('/api/platform/governance-rules', [PlatformGovernance::class, 'index']);
$router->post('/api/platform/governance-rules', [PlatformGovernance::class, 'create']);
$router->put('/api/platform/governance-rules/{rule_id}', [PlatformGovernance::class, 'update']);
$router->delete('/api/platform/governance-rules/{rule_id}', [PlatformGovernance::class, 'delete']);
$router->post('/api/platform/governance-rules/batch', [PlatformGovernance::class, 'batch']);
$router->get('/api/platform/effective-features', [PlatformGovernance::class, 'effective']);
$router->get('/api/platform/ai/status', [PlatformAiKnowledge::class, 'status']);
$router->get('/api/platform/ai-knowledge', [PlatformAiKnowledge::class, 'index']);
$router->post('/api/platform/ai-knowledge', [PlatformAiKnowledge::class, 'create']);
$router->get('/api/platform/ai-knowledge/{document_id}', [PlatformAiKnowledge::class, 'show']);
$router->put('/api/platform/ai-knowledge/{document_id}', [PlatformAiKnowledge::class, 'update']);
$router->delete('/api/platform/ai-knowledge/{document_id}', [PlatformAiKnowledge::class, 'delete']);
$router->get('/api/platform/community/posts', [PlatformCommunity::class, 'posts']);
$router->get('/api/platform/software-updates', [PlatformLifecycle::class, 'updates']);
$router->post('/api/platform/software-updates', [PlatformLifecycle::class, 'createUpdate']);
$router->put('/api/platform/software-updates/{policy_id}', [PlatformLifecycle::class, 'updateUpdate']);
$router->delete('/api/platform/software-updates/{policy_id}', [PlatformLifecycle::class, 'deleteUpdate']);
$router->get('/api/platform/maintenances', [PlatformLifecycle::class, 'maintenances']);
$router->post('/api/platform/maintenances', [PlatformLifecycle::class, 'createMaintenance']);
$router->put('/api/platform/maintenances/{policy_id}', [PlatformLifecycle::class, 'updateMaintenance']);
$router->delete('/api/platform/maintenances/{policy_id}', [PlatformLifecycle::class, 'deleteMaintenance']);
$router->get('/api/platform/festival-themes', [PlatformLifecycle::class, 'festivalThemes']);
$router->post('/api/platform/festival-themes', [PlatformLifecycle::class, 'createFestivalTheme']);
$router->put('/api/platform/festival-themes/{policy_id}', [PlatformLifecycle::class, 'updateFestivalTheme']);
$router->delete('/api/platform/festival-themes/{policy_id}', [PlatformLifecycle::class, 'deleteFestivalTheme']);
$router->get('/api/platform/poll-categories', [PlatformPoll::class, 'categories']);
$router->post('/api/platform/poll-categories', [PlatformPoll::class, 'createCategory']);
$router->put('/api/platform/poll-categories/{category_id}', [PlatformPoll::class, 'updateCategory']);
$router->delete('/api/platform/poll-categories/{category_id}', [PlatformPoll::class, 'deleteCategory']);
$router->get('/api/platform/polls', [PlatformPoll::class, 'polls']);
$router->post('/api/platform/polls', [PlatformPoll::class, 'createPoll']);
$router->get('/api/platform/polls/{poll_id}', [PlatformPoll::class, 'show']);
$router->post('/api/platform/polls/{poll_id}/vote', [PlatformPoll::class, 'vote']);
$router->post('/api/platform/polls/{poll_id}/close', [PlatformPoll::class, 'close']);
$router->delete('/api/platform/polls/{poll_id}', [PlatformPoll::class, 'delete']);
$router->post('/api/platform/community/posts', [PlatformCommunity::class, 'create']);
$router->get('/api/platform/community/posts/{post_id}', [PlatformCommunity::class, 'show']);
$router->post('/api/platform/community/posts/{post_id}/comments', [PlatformCommunity::class, 'comment']);
$router->post('/api/platform/community/posts/{post_id}/reactions', [PlatformCommunity::class, 'reaction']);
$router->delete('/api/platform/community/posts/{post_id}', [PlatformCommunity::class, 'delete']);
$router->get('/api/platform/activities/balance', [PlatformActivity::class, 'balance']);
$router->get('/api/platform/activities', [PlatformActivity::class, 'index']);
$router->post('/api/platform/activities', [PlatformActivity::class, 'create']);
$router->get('/api/platform/activities/{activity_id}', [PlatformActivity::class, 'show']);
$router->post('/api/platform/activities/{activity_id}/claim', [PlatformActivity::class, 'claim']);
$router->post('/api/platform/activities/{activity_id}/draw', [PlatformActivity::class, 'draw']);
$router->post('/api/platform/activities/{activity_id}/submit', [PlatformActivity::class, 'submit']);
$router->post('/api/platform/activities/{activity_id}/award', [PlatformActivity::class, 'award']);
$router->post('/api/platform/activities/{activity_id}/close', [PlatformActivity::class, 'close']);
$router->post('/api/platform/activities/{activity_id}/cancel', [PlatformActivity::class, 'cancel']);

// Level 1 manages independent level 2 authorized platforms.
$router->get('/api/platform/operators', [PlatformOperator::class, 'index']);
$router->post('/api/platform/operators', [PlatformOperator::class, 'create']);
$router->put('/api/platform/operators/batch-entitlement', [PlatformOperator::class, 'batchEntitlement']);
$router->get('/api/platform/operators/{operator_id}', [PlatformOperator::class, 'show']);
$router->put('/api/platform/operators/{operator_id}', [PlatformOperator::class, 'update']);
$router->put('/api/platform/operators/{operator_id}/entitlement', [PlatformOperator::class, 'entitlement']);
$router->put('/api/platform/operators/{operator_id}/password', [PlatformOperator::class, 'resetPassword']);
$router->post('/api/platform/operators/{operator_id}/ban', [PlatformOperator::class, 'ban']);
$router->post('/api/platform/operators/{operator_id}/unban', [PlatformOperator::class, 'unban']);
$router->delete('/api/platform/operators/{operator_id}', [PlatformOperator::class, 'delete']);
$router->get('/api/platform/operators/{operator_id}/settings', [PlatformOperator::class, 'settings']);
$router->put('/api/platform/operators/{operator_id}/settings', [PlatformOperator::class, 'saveSettings']);
$router->get('/api/platform/operators/{operator_id}/permissions', [PlatformOperator::class, 'permissionList']);
$router->put('/api/platform/operators/{operator_id}/permissions', [PlatformOperator::class, 'savePermissions']);

// Level 1/2 manages scoped level 3 admins and all their applications.
$router->get('/api/platform/admins', [PlatformAdmin::class, 'index']);
$router->post('/api/platform/admins', [PlatformAdmin::class, 'create']);
$router->put('/api/platform/admins/batch-entitlement', [PlatformAdmin::class, 'batchEntitlement']);
$router->get('/api/platform/admins/{admin_id}', [PlatformAdmin::class, 'show']);
$router->put('/api/platform/admins/{admin_id}', [PlatformAdmin::class, 'update']);
$router->put('/api/platform/admins/{admin_id}/password', [PlatformAdmin::class, 'resetPassword']);
$router->post('/api/platform/admins/{admin_id}/ban', [PlatformAdmin::class, 'ban']);
$router->post('/api/platform/admins/{admin_id}/unban', [PlatformAdmin::class, 'unban']);
$router->delete('/api/platform/admins/{admin_id}', [PlatformAdmin::class, 'delete']);
$router->put('/api/platform/admins/{admin_id}/entitlement', [PlatformAdmin::class, 'entitlement']);
$router->get('/api/platform/admins/{admin_id}/permissions', [PlatformAdmin::class, 'permissionList']);
$router->put('/api/platform/admins/{admin_id}/permissions', [PlatformAdmin::class, 'savePermissions']);
$router->post('/api/platform/admins/{admin_id}/impersonate', [PlatformAdmin::class, 'impersonate']);
$router->get('/api/platform/admins/{admin_id}/apps', [PlatformAdmin::class, 'apps']);
$router->get('/api/platform/apps', [PlatformDashboard::class, 'apps']);
$router->get('/api/platform/apps/{app_id}/users', [PlatformOversight::class, 'users']);
$router->get('/api/platform/apps/{app_id}/users/{user_id}/overview', [PlatformOversight::class, 'overview']);
$router->get('/api/platform/apps/{app_id}/users/{user_id}/permissions', [PlatformOversight::class, 'userPermissions']);
$router->put('/api/platform/apps/{app_id}/users/{user_id}/permissions', [PlatformOversight::class, 'saveUserPermissions']);
$router->get('/api/platform/apps/{app_id}/users/{user_id}/communications', [PlatformOversight::class, 'communications']);
$router->post('/api/platform/apps/{app_id}/users/{user_id}/communications/send', [PlatformOversight::class, 'participate']);
$router->put('/api/platform/apps/{app_id}/users/{user_id}/communications/{message_id}', [PlatformOversight::class, 'updateCommunication']);
$router->delete('/api/platform/apps/{app_id}/users/{user_id}/communications/{message_id}', [PlatformOversight::class, 'deleteCommunication']);
$router->get('/api/platform/apps/{app_id}/communication-takeover-policy', [PlatformOversight::class, 'takeoverPolicy']);
$router->put('/api/platform/apps/{app_id}/communication-takeover-policy', [PlatformOversight::class, 'saveTakeoverPolicy']);
$router->get('/api/platform/apps/{app_id}/communication-takeover-audits', [PlatformOversight::class, 'takeoverAudits']);
$router->get('/api/platform/apps/{app_id}/message-forwards/{forward_id}', [PlatformOversight::class, 'forwardBundle']);
$router->post('/api/platform/apps/{app_id}/red-packets/{packet_id}/force-refund', [PlatformOversight::class, 'forceRefundRedPacket']);
$router->get('/api/platform/apps/{app_id}/uploads', [PlatformOversight::class, 'uploads']);
$router->post('/api/platform/apps/{app_id}/uploads', [PlatformOversight::class, 'upload']);
$router->delete('/api/platform/apps/{app_id}/uploads/{upload_id}', [PlatformOversight::class, 'deleteUpload']);
$router->delete('/api/platform/apps/{app_id}/chat-rooms/{room_id}/assets/{asset_type}/{asset_id}', [PlatformOversight::class, 'deleteGroupAsset']);
$router->get('/api/platform/apps/{app_id}/forum-plates', [PlatformOversight::class, 'forumPlates']);
$router->get('/api/platform/apps/{app_id}/forum-posts', [PlatformOversight::class, 'forumPosts']);
$router->get('/api/platform/apps/{app_id}/forum-posts/{post_id}', [PlatformOversight::class, 'forumPost']);
$router->get('/api/platform/apps/{app_id}/reward-rules', [PlatformReward::class, 'rules']);
$router->put('/api/platform/apps/{app_id}/reward-rules/{scene_code}', [PlatformReward::class, 'updateRule']);
$router->get('/api/platform/apps/{app_id}/reward-events', [PlatformReward::class, 'events']);
$router->post('/api/platform/apps/{app_id}/reward-events/{event_id}/review', [PlatformReward::class, 'review']);
$router->post('/api/platform/apps/{app_id}/rewards/manual-grant', [PlatformReward::class, 'manualGrant']);
$router->get('/api/platform/apps/{app_id}', [PlatformDashboard::class, 'app']);
$router->put('/api/platform/apps/{app_id}', [PlatformDashboard::class, 'updateApp']);
$router->put('/api/platform/apps/{app_id}/settings', [PlatformDashboard::class, 'saveAppSettings']);
$router->delete('/api/platform/apps/{app_id}', [PlatformDashboard::class, 'deleteApp']);

// Level 3 purchase requests and feedback are handled by their direct level 1/2 owner.
$router->get('/api/platform/purchase-orders', [PlatformBilling::class, 'purchaseOrders']);
$router->post('/api/platform/purchase-orders/{order_id}/fulfill', [PlatformBilling::class, 'fulfillPurchaseOrder']);
$router->post('/api/platform/purchase-orders/{order_id}/reject', [PlatformBilling::class, 'rejectPurchaseOrder']);
$router->get('/api/platform/admin-feedbacks', [PlatformBilling::class, 'feedbacks']);
$router->post('/api/platform/admin-feedbacks/{feedback_id}/reply', [PlatformBilling::class, 'replyFeedback']);

// Platform integral products, automatic exchanges, refunds and ledger audit.
$router->get('/api/platform/exchange-products', [PlatformExchange::class, 'products']);
$router->post('/api/platform/exchange-products', [PlatformExchange::class, 'createProduct']);
$router->get('/api/platform/exchange-products/{product_id}', [PlatformExchange::class, 'product']);
$router->put('/api/platform/exchange-products/{product_id}', [PlatformExchange::class, 'updateProduct']);
$router->post('/api/platform/exchange-products/{product_id}/enable', [PlatformExchange::class, 'enableProduct']);
$router->post('/api/platform/exchange-products/{product_id}/disable', [PlatformExchange::class, 'disableProduct']);
$router->delete('/api/platform/exchange-products/{product_id}', [PlatformExchange::class, 'deleteProduct']);
$router->get('/api/platform/exchanges', [PlatformExchange::class, 'orders']);
$router->get('/api/platform/exchanges/{exchange_id}', [PlatformExchange::class, 'order']);
$router->post('/api/platform/exchanges/{exchange_id}/refund', [PlatformExchange::class, 'refund']);
$router->get('/api/platform/balance-logs', [PlatformExchange::class, 'integralLogs']);

// Administrator account.
$router->post('/api/admin/register', [AdminAuth::class, 'register']);
$router->post('/api/admin/login', [AdminAuth::class, 'login']);
$router->post('/api/admin/logout', [AdminAuth::class, 'logout']);
$router->get('/api/admin/me', [AdminAuth::class, 'me']);
$router->get('/api/admin/permissions', [AdminAuth::class, 'permissions']);
$router->put('/api/admin/profile', [AdminAuth::class, 'profile']);
$router->post('/api/admin/profile/avatar', [AdminAuth::class, 'avatar']);
$router->put('/api/admin/password', [AdminAuth::class, 'password']);
$router->get('/api/admin/login-logs', [AdminAuth::class, 'loginLogs']);
$router->get('/api/admin/identity-unbind-requests', [AdminIdentity::class, 'index']);
$router->post('/api/admin/identity-unbind-requests/{request_id}/review', [AdminIdentity::class, 'review']);
$router->get('/api/admin/my-identity-unbind-requests', [AdminIdentity::class, 'mine']);
$router->post('/api/admin/my-identity-unbind-requests', [AdminIdentity::class, 'requestMine']);
$router->get('/api/admin/entitlement', [AdminBilling::class, 'entitlement']);
$router->get('/api/admin/purchase-orders', [AdminBilling::class, 'purchaseOrders']);
$router->post('/api/admin/purchase-orders', [AdminBilling::class, 'createPurchaseOrder']);
$router->get('/api/admin/platform-feedbacks', [AdminBilling::class, 'feedbacks']);
$router->post('/api/admin/platform-feedbacks', [AdminBilling::class, 'createFeedback']);
$router->get('/api/admin/exchange-products', [AdminExchange::class, 'products']);
$router->get('/api/admin/exchange-products/{product_id}', [AdminExchange::class, 'product']);
$router->post('/api/admin/exchanges/quote', [AdminExchange::class, 'quote']);
$router->get('/api/admin/exchanges', [AdminExchange::class, 'orders']);
$router->post('/api/admin/exchanges', [AdminExchange::class, 'exchange']);
$router->get('/api/admin/exchanges/{exchange_id}', [AdminExchange::class, 'order']);
$router->get('/api/admin/balance-logs', [AdminExchange::class, 'integralLogs']);
$router->get('/api/admin/community/posts', [AdminCommunity::class, 'posts']);
$router->post('/api/admin/community/posts', [AdminCommunity::class, 'create']);
$router->get('/api/admin/community/posts/{post_id}', [AdminCommunity::class, 'show']);
$router->post('/api/admin/community/posts/{post_id}/comments', [AdminCommunity::class, 'comment']);
$router->post('/api/admin/community/posts/{post_id}/reactions', [AdminCommunity::class, 'reaction']);
$router->delete('/api/admin/community/posts/{post_id}', [AdminCommunity::class, 'delete']);
$router->get('/api/admin/poll-categories', [AdminPoll::class, 'categories']);
$router->post('/api/admin/poll-categories', [AdminPoll::class, 'createCategory']);
$router->put('/api/admin/poll-categories/{category_id}', [AdminPoll::class, 'updateCategory']);
$router->delete('/api/admin/poll-categories/{category_id}', [AdminPoll::class, 'deleteCategory']);
$router->get('/api/admin/polls', [AdminPoll::class, 'polls']);
$router->post('/api/admin/polls', [AdminPoll::class, 'createPoll']);
$router->get('/api/admin/polls/{poll_id}', [AdminPoll::class, 'show']);
$router->post('/api/admin/polls/{poll_id}/vote', [AdminPoll::class, 'vote']);
$router->post('/api/admin/polls/{poll_id}/close', [AdminPoll::class, 'close']);
$router->delete('/api/admin/polls/{poll_id}', [AdminPoll::class, 'delete']);
$router->get('/api/admin/activities/balance', [AdminActivity::class, 'balance']);
$router->get('/api/admin/activities', [AdminActivity::class, 'index']);
$router->post('/api/admin/activities', [AdminActivity::class, 'create']);
$router->get('/api/admin/activities/{activity_id}', [AdminActivity::class, 'show']);
$router->post('/api/admin/activities/{activity_id}/claim', [AdminActivity::class, 'claim']);
$router->post('/api/admin/activities/{activity_id}/draw', [AdminActivity::class, 'draw']);
$router->post('/api/admin/activities/{activity_id}/submit', [AdminActivity::class, 'submit']);
$router->post('/api/admin/activities/{activity_id}/award', [AdminActivity::class, 'award']);
$router->post('/api/admin/activities/{activity_id}/close', [AdminActivity::class, 'close']);
$router->post('/api/admin/activities/{activity_id}/cancel', [AdminActivity::class, 'cancel']);

// Administrator-owned applications and tenant configuration.
$router->get('/api/admin/apps', [AdminApp::class, 'index']);
$router->post('/api/admin/apps', [AdminApp::class, 'create']);
$router->get('/api/admin/apps/{app_id}', [AdminApp::class, 'show']);
$router->put('/api/admin/apps/{app_id}', [AdminApp::class, 'update']);
$router->post('/api/admin/apps/{app_id}/enable', [AdminApp::class, 'enable']);
$router->post('/api/admin/apps/{app_id}/disable', [AdminApp::class, 'disable']);
$router->delete('/api/admin/apps/{app_id}', [AdminApp::class, 'delete']);
$router->post('/api/admin/apps/{app_id}/secret/reset', [AdminApp::class, 'resetSecret']);
$router->get('/api/admin/apps/{app_id}/settings', [AdminApp::class, 'settings']);
$router->put('/api/admin/apps/{app_id}/settings', [AdminApp::class, 'saveSettings']);
$router->get('/api/admin/apps/{app_id}/features', [AdminApp::class, 'features']);
$router->put('/api/admin/apps/{app_id}/features', [AdminApp::class, 'saveFeatures']);
$router->get('/api/admin/apps/{app_id}/domains', [AdminApp::class, 'domains']);
$router->post('/api/admin/apps/{app_id}/domains', [AdminApp::class, 'createDomain']);
$router->delete('/api/admin/apps/{app_id}/domains/{domain_id}', [AdminApp::class, 'deleteDomain']);
$router->get('/api/admin/apps/{app_id}/ai-knowledge', [AdminAiKnowledge::class, 'index']);
$router->get('/api/admin/apps/{app_id}/ai/status', [AdminAiKnowledge::class, 'status']);
$router->post('/api/admin/apps/{app_id}/ai-knowledge', [AdminAiKnowledge::class, 'create']);
$router->get('/api/admin/apps/{app_id}/ai-knowledge/{document_id}', [AdminAiKnowledge::class, 'show']);
$router->put('/api/admin/apps/{app_id}/ai-knowledge/{document_id}', [AdminAiKnowledge::class, 'update']);
$router->delete('/api/admin/apps/{app_id}/ai-knowledge/{document_id}', [AdminAiKnowledge::class, 'delete']);
$router->get('/api/admin/apps/{app_id}/reward-rules', [AdminReward::class, 'rules']);
$router->put('/api/admin/apps/{app_id}/reward-rules/{scene_code}', [AdminReward::class, 'updateRule']);
$router->get('/api/admin/apps/{app_id}/reward-events', [AdminReward::class, 'events']);
$router->post('/api/admin/apps/{app_id}/reward-events/{event_id}/review', [AdminReward::class, 'review']);
$router->post('/api/admin/apps/{app_id}/rewards/manual-grant', [AdminReward::class, 'manualGrant']);

// User lifecycle, permissions, labels and assets.
$router->post('/api/admin/apps/{app_id}/users/import', [AdminUser::class, 'import']);
$router->get('/api/admin/apps/{app_id}/user-tags', [AdminUser::class, 'tags']);
$router->post('/api/admin/apps/{app_id}/user-tags', [AdminUser::class, 'createTag']);
$router->put('/api/admin/apps/{app_id}/user-tags/{tag_id}', [AdminUser::class, 'updateTag']);
$router->delete('/api/admin/apps/{app_id}/user-tags/{tag_id}', [AdminUser::class, 'deleteTag']);
$router->get('/api/admin/apps/{app_id}/users', [AdminUser::class, 'index']);
$router->post('/api/admin/apps/{app_id}/users', [AdminUser::class, 'create']);
$router->put('/api/admin/apps/{app_id}/users/batch-entitlement', [AdminUser::class, 'batchEntitlement']);
$router->get('/api/admin/apps/{app_id}/users/{user_id}', [AdminUser::class, 'show']);
$router->get('/api/admin/apps/{app_id}/users/{user_id}/permissions', [AdminUser::class, 'permissions']);
$router->put('/api/admin/apps/{app_id}/users/{user_id}/permissions', [AdminUser::class, 'savePermissions']);
$router->get('/api/admin/apps/{app_id}/users/{user_id}/communications', [AdminUser::class, 'communications']);
$router->post('/api/admin/apps/{app_id}/users/{user_id}/communications/send', [AdminUser::class, 'participate']);
$router->put('/api/admin/apps/{app_id}/users/{user_id}/communications/{message_id}', [AdminUser::class, 'updateCommunication']);
$router->delete('/api/admin/apps/{app_id}/users/{user_id}/communications/{message_id}', [AdminUser::class, 'deleteCommunication']);
$router->get('/api/admin/apps/{app_id}/communication-takeover-policy', [AdminUser::class, 'takeoverPolicy']);
$router->put('/api/admin/apps/{app_id}/communication-takeover-policy', [AdminUser::class, 'saveTakeoverPolicy']);
$router->get('/api/admin/apps/{app_id}/communication-takeover-audits', [AdminUser::class, 'takeoverAudits']);
$router->get('/api/admin/apps/{app_id}/message-forwards/{forward_id}', [AdminUser::class, 'forwardBundle']);
$router->put('/api/admin/apps/{app_id}/users/{user_id}', [AdminUser::class, 'update']);
$router->put('/api/admin/apps/{app_id}/users/{user_id}/password', [AdminUser::class, 'resetPassword']);
$router->post('/api/admin/apps/{app_id}/users/{user_id}/ban', [AdminUser::class, 'ban']);
$router->post('/api/admin/apps/{app_id}/users/{user_id}/unban', [AdminUser::class, 'unban']);
$router->delete('/api/admin/apps/{app_id}/users/{user_id}', [AdminUser::class, 'delete']);
$router->put('/api/admin/apps/{app_id}/users/{user_id}/wallet', [AdminUser::class, 'wallet']);
$router->put('/api/admin/apps/{app_id}/users/{user_id}/vip', [AdminUser::class, 'vip']);
$router->put('/api/admin/apps/{app_id}/users/{user_id}/entitlement', [AdminUser::class, 'entitlement']);
$router->get('/api/admin/apps/{app_id}/users/{user_id}/logs', [AdminUser::class, 'logs']);
$router->post('/api/admin/apps/{app_id}/users/{user_id}/tags', [AdminUser::class, 'setTags']);
$router->get('/api/admin/apps/{app_id}/users/{user_id}/transfer-policy', [AdminUser::class, 'transferPolicy']);
$router->put('/api/admin/apps/{app_id}/users/{user_id}/transfer-policy', [AdminUser::class, 'saveTransferPolicy']);

// Documents, notices, versions, banners and remote configuration.
$router->get('/api/admin/apps/{app_id}/documents', [AdminDocument::class, 'index']);
$router->post('/api/admin/apps/{app_id}/documents', [AdminDocument::class, 'create']);
$router->get('/api/admin/apps/{app_id}/documents/{document_id}', [AdminDocument::class, 'show']);
$router->put('/api/admin/apps/{app_id}/documents/{document_id}', [AdminDocument::class, 'update']);
$router->delete('/api/admin/apps/{app_id}/documents/{document_id}', [AdminDocument::class, 'delete']);
$router->post('/api/admin/apps/{app_id}/documents/{document_id}/restore', [AdminDocument::class, 'restore']);
$router->get('/api/admin/apps/{app_id}/document-shares', [AdminDocument::class, 'shares']);
$router->put('/api/admin/apps/{app_id}/document-rules', [AdminDocument::class, 'rules']);
$router->get('/api/admin/apps/{app_id}/notices', [AdminContent::class, 'notices']);
$router->post('/api/admin/apps/{app_id}/notices', [AdminContent::class, 'createNotice']);
$router->put('/api/admin/apps/{app_id}/notices/{notice_id}', [AdminContent::class, 'updateNotice']);
$router->delete('/api/admin/apps/{app_id}/notices/{notice_id}', [AdminContent::class, 'deleteNotice']);
$router->get('/api/admin/apps/{app_id}/versions', [AdminContent::class, 'versions']);
$router->put('/api/admin/apps/{app_id}/versions', [AdminContent::class, 'publishVersion']);
$router->get('/api/admin/apps/{app_id}/maintenances', [AdminLifecycle::class, 'maintenances']);
$router->post('/api/admin/apps/{app_id}/maintenances', [AdminLifecycle::class, 'createMaintenance']);
$router->put('/api/admin/apps/{app_id}/maintenances/{policy_id}', [AdminLifecycle::class, 'updateMaintenance']);
$router->delete('/api/admin/apps/{app_id}/maintenances/{policy_id}', [AdminLifecycle::class, 'deleteMaintenance']);
$router->get('/api/admin/apps/{app_id}/festival-themes', [AdminLifecycle::class, 'festivalThemes']);
$router->post('/api/admin/apps/{app_id}/festival-themes', [AdminLifecycle::class, 'createFestivalTheme']);
$router->put('/api/admin/apps/{app_id}/festival-themes/{policy_id}', [AdminLifecycle::class, 'updateFestivalTheme']);
$router->delete('/api/admin/apps/{app_id}/festival-themes/{policy_id}', [AdminLifecycle::class, 'deleteFestivalTheme']);
$router->get('/api/admin/apps/{app_id}/banners', [AdminContent::class, 'banners']);
$router->post('/api/admin/apps/{app_id}/banners', [AdminContent::class, 'createBanner']);
$router->put('/api/admin/apps/{app_id}/banners/{banner_id}', [AdminContent::class, 'updateBanner']);
$router->delete('/api/admin/apps/{app_id}/banners/{banner_id}', [AdminContent::class, 'deleteBanner']);
$router->get('/api/admin/apps/{app_id}/remote-configs', [AdminContent::class, 'remoteConfigs']);
$router->put('/api/admin/apps/{app_id}/remote-configs', [AdminContent::class, 'saveRemoteConfigs']);

// Resource hall, application store and forum moderation.
$router->get('/api/admin/apps/{app_id}/resource-categories', [AdminResource::class, 'categories']);
$router->post('/api/admin/apps/{app_id}/resource-categories', [AdminResource::class, 'createCategory']);
$router->put('/api/admin/apps/{app_id}/resource-categories/{category_id}', [AdminResource::class, 'updateCategory']);
$router->delete('/api/admin/apps/{app_id}/resource-categories/{category_id}', [AdminResource::class, 'deleteCategory']);
$router->get('/api/admin/apps/{app_id}/resources', [AdminResource::class, 'resources']);
$router->put('/api/admin/apps/{app_id}/resources/{resource_id}/audit', [AdminResource::class, 'audit']);
$router->put('/api/admin/apps/{app_id}/resources/{resource_id}', [AdminResource::class, 'updateResource']);
$router->delete('/api/admin/apps/{app_id}/resources/{resource_id}', [AdminResource::class, 'deleteResource']);
$router->get('/api/admin/apps/{app_id}/store-categories', [AdminResource::class, 'storeCategories']);
$router->post('/api/admin/apps/{app_id}/store-categories', [AdminResource::class, 'createStoreCategory']);
  $router->get('/api/admin/apps/{app_id}/store-apps', [AdminResource::class, 'storeApps']);
  $router->post('/api/admin/apps/{app_id}/store-apps', [AdminResource::class, 'createStoreApp']);
  $router->put('/api/admin/apps/{app_id}/store-apps/{store_app_id}/audit', [AdminResource::class, 'auditStoreApp']);
  $router->get('/api/admin/apps/{app_id}/forum-plates', [AdminForum::class, 'plates']);
$router->get('/api/admin/apps/{app_id}/forum-categories', [AdminForumStructure::class, 'categories']);
$router->post('/api/admin/apps/{app_id}/forum-categories', [AdminForumStructure::class, 'createCategory']);
$router->put('/api/admin/apps/{app_id}/forum-categories/{category_id}', [AdminForumStructure::class, 'updateCategory']);
$router->delete('/api/admin/apps/{app_id}/forum-categories/{category_id}', [AdminForumStructure::class, 'deleteCategory']);
$router->get('/api/admin/apps/{app_id}/forum-tags', [AdminForumStructure::class, 'tags']);
$router->post('/api/admin/apps/{app_id}/forum-tags', [AdminForumStructure::class, 'createTag']);
$router->put('/api/admin/apps/{app_id}/forum-tags/{tag_id}', [AdminForumStructure::class, 'updateTag']);
$router->delete('/api/admin/apps/{app_id}/forum-tags/{tag_id}', [AdminForumStructure::class, 'deleteTag']);
$router->get('/api/admin/apps/{app_id}/forum-structure-requests', [AdminForumStructure::class, 'requests']);
$router->post('/api/admin/apps/{app_id}/forum-structure-requests/{request_id}/review', [AdminForumStructure::class, 'reviewRequest']);
$router->get('/api/admin/apps/{app_id}/forum-moderators', [AdminForumStructure::class, 'moderators']);
$router->put('/api/admin/apps/{app_id}/forum-moderators/{moderator_id}', [AdminForumStructure::class, 'updateModerator']);
$router->get('/api/admin/apps/{app_id}/bounty-categories', [AdminBounty::class, 'categories']);
$router->post('/api/admin/apps/{app_id}/bounty-categories', [AdminBounty::class, 'createCategory']);
$router->put('/api/admin/apps/{app_id}/bounty-categories/{category_id}', [AdminBounty::class, 'updateCategory']);
$router->delete('/api/admin/apps/{app_id}/bounty-categories/{category_id}', [AdminBounty::class, 'deleteCategory']);
$router->get('/api/admin/apps/{app_id}/bounty-category-requests', [AdminBounty::class, 'categoryRequests']);
$router->post('/api/admin/apps/{app_id}/bounty-category-requests/{request_id}/review', [AdminBounty::class, 'reviewCategoryRequest']);
$router->get('/api/admin/apps/{app_id}/bounties', [AdminBounty::class, 'index']);
$router->get('/api/admin/apps/{app_id}/bounties/{bounty_id}', [AdminBounty::class, 'show']);
$router->put('/api/admin/apps/{app_id}/bounties/{bounty_id}', [AdminBounty::class, 'update']);
$router->put('/api/admin/apps/{app_id}/bounties/{bounty_id}/audit', [AdminBounty::class, 'audit']);
$router->post('/api/admin/apps/{app_id}/bounties/{bounty_id}/cancel', [AdminBounty::class, 'cancel']);
$router->delete('/api/admin/apps/{app_id}/bounties/{bounty_id}', [AdminBounty::class, 'delete']);
$router->post('/api/admin/apps/{app_id}/forum-plates', [AdminForum::class, 'createPlate']);
$router->put('/api/admin/apps/{app_id}/forum-plates/{plate_id}', [AdminForum::class, 'updatePlate']);
$router->post('/api/admin/apps/{app_id}/forum-plates/{plate_id}/avatar', [AdminForum::class, 'plateAvatar']);
$router->get('/api/admin/apps/{app_id}/forum-posts', [AdminForum::class, 'posts']);
$router->get('/api/admin/apps/{app_id}/forum-posts/{post_id}', [AdminForum::class, 'showPost']);
$router->put('/api/admin/apps/{app_id}/forum-posts/{post_id}', [AdminForum::class, 'updatePost']);
$router->put('/api/admin/apps/{app_id}/forum-posts/{post_id}/top', [AdminForum::class, 'top']);
$router->put('/api/admin/apps/{app_id}/forum-posts/{post_id}/essence', [AdminForum::class, 'essence']);
$router->put('/api/admin/apps/{app_id}/forum-posts/{post_id}/lock', [AdminForum::class, 'lock']);
$router->put('/api/admin/apps/{app_id}/forum-posts/{post_id}/audit', [AdminForum::class, 'audit']);
$router->delete('/api/admin/apps/{app_id}/forum-posts/{post_id}', [AdminForum::class, 'deletePost']);
$router->get('/api/admin/apps/{app_id}/forum-comments', [AdminForum::class, 'comments']);
$router->get('/api/admin/apps/{app_id}/forum-comments/{comment_id}', [AdminForum::class, 'showComment']);
$router->put('/api/admin/apps/{app_id}/forum-comments/{comment_id}/audit', [AdminForum::class, 'auditComment']);
$router->delete('/api/admin/apps/{app_id}/forum-comments/{comment_id}', [AdminForum::class, 'deleteComment']);
$router->get('/api/admin/apps/{app_id}/moments', [AdminContentModeration::class, 'moments']);
$router->get('/api/admin/apps/{app_id}/moments/{moment_id}', [AdminContentModeration::class, 'showMoment']);
$router->put('/api/admin/apps/{app_id}/moments/{moment_id}/audit', [AdminContentModeration::class, 'auditMoment']);
$router->get('/api/admin/apps/{app_id}/moment-comments', [AdminContentModeration::class, 'comments']);
$router->get('/api/admin/apps/{app_id}/moment-comments/{comment_id}', [AdminContentModeration::class, 'showComment']);
$router->put('/api/admin/apps/{app_id}/moment-comments/{comment_id}/audit', [AdminContentModeration::class, 'auditComment']);
$router->get('/api/admin/apps/{app_id}/forum-report-tags', [AdminForum::class, 'reportTags']);
$router->post('/api/admin/apps/{app_id}/forum-report-tags', [AdminForum::class, 'createReportTag']);
$router->put('/api/admin/apps/{app_id}/forum-report-tags/{tag_id}', [AdminForum::class, 'updateReportTag']);
$router->delete('/api/admin/apps/{app_id}/forum-report-tags/{tag_id}', [AdminForum::class, 'deleteReportTag']);
$router->get('/api/admin/apps/{app_id}/reports', [AdminForum::class, 'reports']);
$router->put('/api/admin/apps/{app_id}/reports/{report_id}', [AdminForum::class, 'handleReport']);

// Communication, customer service and chat room operations.
$router->post('/api/admin/apps/{app_id}/system-messages', [AdminCommunication::class, 'systemMessage']);
$router->get('/api/admin/apps/{app_id}/messages', [AdminCommunication::class, 'messages']);
$router->get('/api/admin/apps/{app_id}/service-sessions', [AdminCommunication::class, 'serviceSessions']);
$router->get('/api/admin/apps/{app_id}/service-sessions/{session_id}/messages', [AdminCommunication::class, 'serviceMessages']);
$router->post('/api/admin/apps/{app_id}/service-sessions/{session_id}/reply', [AdminCommunication::class, 'serviceReply']);
$router->post('/api/admin/apps/{app_id}/service-sessions/{session_id}/close', [AdminCommunication::class, 'closeServiceSession']);
$router->get('/api/admin/apps/{app_id}/chat-rooms', [AdminGroup::class, 'index']);
$router->post('/api/admin/apps/{app_id}/chat-rooms', [AdminGroup::class, 'create']);
$router->get('/api/admin/apps/{app_id}/chat-rooms/{room_id}', [AdminGroup::class, 'show']);
$router->put('/api/admin/apps/{app_id}/chat-rooms/{room_id}', [AdminGroup::class, 'update']);
$router->delete('/api/admin/apps/{app_id}/chat-rooms/{room_id}', [AdminGroup::class, 'delete']);
$router->get('/api/admin/apps/{app_id}/chat-rooms/{room_id}/members', [AdminGroup::class, 'members']);
$router->post('/api/admin/apps/{app_id}/chat-rooms/{room_id}/members', [AdminGroup::class, 'addMember']);
$router->put('/api/admin/apps/{app_id}/chat-rooms/{room_id}/members/{user_id}', [AdminGroup::class, 'updateMember']);
$router->put('/api/admin/apps/{app_id}/chat-rooms/{room_id}/members/{user_id}/mute', [AdminGroup::class, 'muteMember']);
$router->delete('/api/admin/apps/{app_id}/chat-rooms/{room_id}/members/{user_id}', [AdminGroup::class, 'removeMember']);
$router->get('/api/admin/apps/{app_id}/chat-rooms/{room_id}/messages', [AdminGroup::class, 'messages']);
$router->delete('/api/admin/apps/{app_id}/chat-rooms/{room_id}/messages/{message_id}', [AdminGroup::class, 'deleteMessage']);
$router->delete('/api/admin/apps/{app_id}/chat-rooms/{room_id}/assets/{asset_type}/{asset_id}', [AdminGroup::class, 'deleteAsset']);
$router->get('/api/admin/apps/{app_id}/chat-rooms/{room_id}/join-requests', [AdminGroup::class, 'joinRequests']);
$router->post('/api/admin/apps/{app_id}/chat-rooms/{room_id}/join-requests/{request_id}/decision', [AdminGroup::class, 'decideJoinRequest']);

// Cards, payments, orders and interactive commerce.
$router->get('/api/admin/apps/{app_id}/card-batches', [AdminCard::class, 'batches']);
$router->post('/api/admin/apps/{app_id}/card-batches', [AdminCard::class, 'createBatch']);
$router->put('/api/admin/apps/{app_id}/card-batches/{batch_id}', [AdminCard::class, 'updateBatch']);
$router->get('/api/admin/apps/{app_id}/cards', [AdminCard::class, 'cards']);
$router->put('/api/admin/apps/{app_id}/cards/{card_id}', [AdminCard::class, 'updateCard']);
$router->get('/api/admin/apps/{app_id}/card-redeem-logs', [AdminCard::class, 'redeemLogs']);
$router->get('/api/admin/apps/{app_id}/card-login-bindings', [AdminCard::class, 'loginBindings']);
$router->get('/api/admin/apps/{app_id}/orders', [AdminCommerce::class, 'orders']);
$router->get('/api/admin/apps/{app_id}/payments', [AdminCommerce::class, 'payments']);
$router->get('/api/admin/apps/{app_id}/payment-channels', [AdminCommerce::class, 'paymentChannels']);
$router->put('/api/admin/apps/{app_id}/payment-channels', [AdminCommerce::class, 'savePaymentChannel']);
$router->get('/api/admin/apps/{app_id}/shop-goods', [AdminCommerce::class, 'goods']);
$router->post('/api/admin/apps/{app_id}/shop-goods', [AdminCommerce::class, 'createGoods']);
$router->put('/api/admin/apps/{app_id}/shop-goods/{goods_id}', [AdminCommerce::class, 'updateGoods']);
$router->delete('/api/admin/apps/{app_id}/shop-goods/{goods_id}', [AdminCommerce::class, 'deleteGoods']);
$router->get('/api/admin/apps/{app_id}/red-packets', [AdminCommerce::class, 'redPackets']);
$router->post('/api/admin/apps/{app_id}/red-packets/{packet_id}/force-refund', [AdminCommerce::class, 'forceRefundRedPacket']);
$router->get('/api/admin/apps/{app_id}/lottery-prizes', [AdminCommerce::class, 'lotteryPrizes']);
$router->post('/api/admin/apps/{app_id}/lottery-prizes', [AdminCommerce::class, 'saveLotteryPrize']);
$router->delete('/api/admin/apps/{app_id}/lottery-prizes/{prize_id}', [AdminCommerce::class, 'deleteLotteryPrize']);
$router->get('/api/admin/apps/{app_id}/votes', [AdminCommerce::class, 'votes']);
$router->post('/api/admin/apps/{app_id}/votes', [AdminCommerce::class, 'createVote']);
$router->post('/api/admin/apps/{app_id}/votes/{vote_id}/close', [AdminCommerce::class, 'closeVote']);

// Remote files, feedback, bot knowledge and observability.
$router->post('/api/admin/apps/{app_id}/remote-files/folders', [AdminFileFeedback::class, 'createFolder']);
$router->get('/api/admin/apps/{app_id}/remote-files', [AdminFileFeedback::class, 'files']);
$router->post('/api/admin/apps/{app_id}/remote-files', [AdminFileFeedback::class, 'createFile']);
$router->put('/api/admin/apps/{app_id}/remote-files/{file_id}', [AdminFileFeedback::class, 'updateFile']);
$router->delete('/api/admin/apps/{app_id}/remote-files/{file_id}', [AdminFileFeedback::class, 'deleteFile']);
$router->get('/api/admin/apps/{app_id}/remote-files/{file_id}/versions', [AdminFileFeedback::class, 'versions']);
$router->get('/api/admin/apps/{app_id}/feedbacks', [AdminFileFeedback::class, 'feedbacks']);
$router->post('/api/admin/apps/{app_id}/feedbacks/{feedback_id}/reply', [AdminFileFeedback::class, 'replyFeedback']);
$router->get('/api/admin/apps/{app_id}/uploads', [AdminFileFeedback::class, 'uploads']);
$router->post('/api/admin/apps/{app_id}/uploads', [AdminFileFeedback::class, 'upload']);
$router->delete('/api/admin/apps/{app_id}/uploads/{upload_id}', [AdminFileFeedback::class, 'deleteUpload']);
$router->get('/api/admin/apps/{app_id}/bot-qa', [AdminFileFeedback::class, 'botQa']);
$router->post('/api/admin/apps/{app_id}/bot-qa', [AdminFileFeedback::class, 'saveBotQa']);
$router->delete('/api/admin/apps/{app_id}/bot-qa/{qa_id}', [AdminFileFeedback::class, 'deleteBotQa']);
$router->get('/api/admin/apps/{app_id}/statistics', [AdminStatistics::class, 'overview']);
$router->get('/api/admin/apps/{app_id}/withdrawals', [AdminSocial::class, 'withdrawals']);
$router->post('/api/admin/apps/{app_id}/withdrawals/{withdrawal_id}/review', [AdminSocial::class, 'reviewWithdrawal']);
$router->get('/api/admin/apps/{app_id}/api-logs', [AdminStatistics::class, 'apiLogs']);
$router->get('/api/admin/apps/{app_id}/operation-logs', [AdminStatistics::class, 'operationLogs']);

// User identity, profile, sign-in, invitation and wallet.
$router->post('/api/user/register', [UserAuth::class, 'register']);
$router->post('/api/user/login', [UserAuth::class, 'login']);
$router->post('/api/user/logout', [UserAuth::class, 'logout']);
$router->post('/api/user/token/refresh', [UserAuth::class, 'refresh']);
$router->get('/api/user/me', [UserAuth::class, 'me']);
$router->get('/api/user/permissions', [UserAuth::class, 'permissions']);
$router->post('/api/user/heartbeat', [UserAuth::class, 'heartbeat']);
$router->get('/api/user/identity-unbind-requests', [UserIdentity::class, 'index']);
$router->post('/api/user/identity-unbind-requests', [UserIdentity::class, 'create']);
$router->put('/api/user/profile', [UserAuth::class, 'profile']);
$router->post('/api/user/profile/avatar', [UserAuth::class, 'avatar']);
$router->get('/api/user/profile/avatar-history', [UserAuth::class, 'avatarHistory']);
$router->post('/api/user/profile/avatar-history/{history_id}/switch', [UserAuth::class, 'switchAvatar']);
$router->put('/api/user/password', [UserAuth::class, 'password']);
$router->post('/api/user/password/reset/code', [UserAuth::class, 'issuePasswordResetCode']);
$router->post('/api/user/password/reset', [UserAuth::class, 'resetPassword']);
$router->post('/api/user/sign', [UserAuth::class, 'sign']);
$router->get('/api/user/wallet', [UserAuth::class, 'wallet']);
$router->get('/api/user/wallet/logs', [UserAuth::class, 'walletLogs']);
$router->post('/api/user/wallet/purchases', [UserAuth::class, 'purchase']);
$router->get('/api/user/wallet/purchases', [UserAuth::class, 'purchases']);
$router->get('/api/user/logs', [UserAuth::class, 'logs']);
$router->post('/api/user/invite-code', [UserAuth::class, 'inviteCode']);
$router->get('/api/user/invite-code', [UserAuth::class, 'inviteCode']);
$router->get('/api/user/invites', [UserAuth::class, 'invites']);
$router->get('/api/user/notices', [UserNotice::class, 'index']);
$router->get('/api/user/rankings', [UserAuth::class, 'rankings']);
$router->post('/api/user/wallet/transfer', [UserCommerce::class, 'transfer']);
$router->get('/api/user/activities/balance', [UserActivity::class, 'balance']);
$router->get('/api/user/activities', [UserActivity::class, 'index']);
$router->get('/api/user/activities/{activity_id}', [UserActivity::class, 'show']);
$router->post('/api/user/activities/{activity_id}/claim', [UserActivity::class, 'claim']);
$router->post('/api/user/activities/{activity_id}/draw', [UserActivity::class, 'draw']);
$router->post('/api/user/activities/{activity_id}/submit', [UserActivity::class, 'submit']);
$router->get('/api/user/users/search', [UserSocial::class, 'searchUsers']);
$router->get('/api/user/profiles/{user_id}', [UserSocial::class, 'profile']);
$router->post('/api/user/profiles/{user_id}/follow', [UserSocial::class, 'follow']);
$router->get('/api/user/profiles/{user_id}/follow-status', [UserSocial::class, 'followStatus']);
$router->post('/api/user/profiles/{user_id}/likes', [UserSocial::class, 'likeProfile']);
$router->delete('/api/user/profiles/{user_id}/likes', [UserSocial::class, 'unlikeProfile']);
$router->get('/api/user/following', [UserSocial::class, 'following']);
$router->get('/api/user/followers', [UserSocial::class, 'followers']);
$router->get('/api/user/blacklist', [UserSocial::class, 'blacklist']);
$router->post('/api/user/blacklist/{user_id}', [UserSocial::class, 'toggleBlacklist']);
$router->get('/api/user/notifications', [UserSocial::class, 'notifications']);
$router->post('/api/user/notifications/read-all', [UserSocial::class, 'readAll']);
$router->post('/api/user/notifications/groups/{group_key}/read', [UserSocial::class, 'readNotificationGroup']);
$router->post('/api/user/notifications/{notification_id}/read', [UserSocial::class, 'readNotification']);
$router->get('/api/user/withdrawals', [UserSocial::class, 'withdrawals']);
$router->post('/api/user/withdrawals', [UserSocial::class, 'createWithdrawal']);
$router->post('/api/user/withdrawals/{withdrawal_id}/cancel', [UserSocial::class, 'cancelWithdrawal']);

// User notes and fixed-code sharing. Admin programmable documents use separate admin routes.
$router->get('/api/user/moments', [UserMoment::class, 'index']);
$router->post('/api/user/moments', [UserMoment::class, 'create']);
$router->get('/api/user/moments/{moment_id}', [UserMoment::class, 'show']);
$router->put('/api/user/moments/{moment_id}', [UserMoment::class, 'update']);
$router->put('/api/user/moments/{moment_id}/visibility', [UserMoment::class, 'updateVisibility']);
$router->delete('/api/user/moments/{moment_id}', [UserMoment::class, 'delete']);
$router->post('/api/user/moments/{moment_id}/restore', [UserMoment::class, 'restore']);
$router->post('/api/user/moments/{moment_id}/pin', [UserMoment::class, 'setPin']);
$router->post('/api/user/moments/{moment_id}/like', [UserMoment::class, 'toggleLike']);
$router->get('/api/user/moments/{moment_id}/likes', [UserMoment::class, 'likes']);
$router->get('/api/user/moments/{moment_id}/comments', [UserMoment::class, 'comments']);
$router->post('/api/user/moments/{moment_id}/comments', [UserMoment::class, 'createComment']);
$router->post('/api/user/moments/{moment_id}/comments/{comment_id}/like', [UserMoment::class, 'toggleCommentLike']);
$router->delete('/api/user/moments/{moment_id}/comments/{comment_id}', [UserMoment::class, 'deleteComment']);
$router->post('/api/user/moments/{moment_id}/favorite', [UserMoment::class, 'toggleFavorite']);
$router->post('/api/user/moments/{moment_id}/forward', [UserMoment::class, 'forward']);

$router->get('/api/user/notes', [UserDocument::class, 'index']);
$router->post('/api/user/notes', [UserDocument::class, 'create']);
$router->get('/api/user/notes/{document_id}', [UserDocument::class, 'show']);
$router->put('/api/user/notes/{document_id}', [UserDocument::class, 'update']);
$router->post('/api/user/notes/{document_id}/favorite', [UserDocument::class, 'toggleFavorite']);
$router->delete('/api/user/notes/{document_id}', [UserDocument::class, 'delete']);
$router->get('/api/user/notes/{document_id}/share', [UserDocument::class, 'currentShare']);
$router->post('/api/user/notes/{document_id}/share', [UserDocument::class, 'share']);
$router->delete('/api/user/note-shares/{share_id}', [UserDocument::class, 'cancelShare']);
$router->post('/api/user/note-folders', [UserDocument::class, 'createFolder']);
$router->put('/api/user/note-folders/{folder_id}', [UserDocument::class, 'updateFolder']);
$router->delete('/api/user/note-folders/{folder_id}', [UserDocument::class, 'deleteFolder']);

    // User resources, application store and forum.
    $router->get('/api/user/resource-categories', [UserResource::class, 'categories']);
    $router->get('/api/user/resource-submission-policy', [UserResource::class, 'submissionPolicy']);
    $router->get('/api/user/resources', [UserResource::class, 'resources']);
$router->post('/api/user/resources', [UserResource::class, 'submit']);
$router->get('/api/user/resources/{resource_id}', [UserResource::class, 'showResource']);
$router->post('/api/user/resources/{resource_id}/buy', [UserResource::class, 'buy']);
$router->post('/api/user/resources/{resource_id}/comments', [UserResource::class, 'comment']);
$router->post('/api/user/resources/{resource_id}/rating', [UserResource::class, 'rating']);
$router->post('/api/user/resources/{resource_id}/reactions', [UserResource::class, 'resourceReaction']);
$router->get('/api/user/favorites/resources', [UserResource::class, 'favoriteResources']);
$router->get('/api/user/favorites', [UserFavorite::class, 'index']);
$router->get('/api/user/reward-rules', [UserReward::class, 'rules']);
$router->get('/api/user/reward-events', [UserReward::class, 'events']);
$router->get('/api/user/store-categories', [UserResource::class, 'storeCategories']);
$router->get('/api/user/store-submission-policy', [UserResource::class, 'storeSubmissionPolicy']);
$router->get('/api/user/store-apps', [UserResource::class, 'storeApps']);
$router->post('/api/user/store-apps', [UserResource::class, 'submitStoreApp']);
$router->get('/api/user/store-apps/{store_app_id}', [UserResource::class, 'showStoreApp']);
$router->post('/api/user/store-apps/{store_app_id}/reactions', [UserResource::class, 'storeReaction']);
$router->get('/api/user/favorites/store-apps', [UserResource::class, 'favoriteStoreApps']);
$router->get('/api/user/favorites/uploads', [UserFileFeedback::class, 'favoriteUploads']);
$router->get('/api/user/forum-plates', [UserForum::class, 'plates']);
$router->get('/api/user/forum-categories', [UserForumStructure::class, 'categories']);
$router->get('/api/user/forum-tags', [UserForumStructure::class, 'tags']);
$router->get('/api/user/forum-structure-requests', [UserForumStructure::class, 'requests']);
$router->post('/api/user/forum-structure-requests', [UserForumStructure::class, 'createRequest']);
$router->get('/api/user/forum-posts', [UserForum::class, 'posts']);
$router->post('/api/user/forum-posts', [UserForum::class, 'createPost']);
$router->get('/api/user/forum-posts/mine', [UserForum::class, 'myPosts']);
$router->get('/api/user/forum-posts/purchased', [UserForum::class, 'purchasedPosts']);
$router->get('/api/user/forum-posts/following', [UserForum::class, 'followingPosts']);
$router->get('/api/user/forum-posts/liked', [UserForum::class, 'likedPosts']);
$router->get('/api/user/forum-report-tags', [UserForum::class, 'reportTags']);
$router->get('/api/user/forum-reports', [UserForum::class, 'myReports']);
$router->get('/api/user/forum-posts/{post_id}', [UserForum::class, 'showPost']);
$router->put('/api/user/forum-posts/{post_id}', [UserForum::class, 'updatePost']);
$router->delete('/api/user/forum-posts/{post_id}', [UserForum::class, 'deletePost']);
$router->post('/api/user/forum-posts/{post_id}/comments', [UserForum::class, 'comment']);
$router->get('/api/user/forum-posts/{post_id}/comments', [UserForum::class, 'comments']);
$router->get('/api/user/forum-posts/{post_id}/likes', [UserForum::class, 'likes']);
$router->post('/api/user/forum-posts/{post_id}/like', [UserForum::class, 'like']);
$router->post('/api/user/forum-posts/{post_id}/favorite', [UserForum::class, 'favorite']);
$router->get('/api/user/forum-favorites', [UserForum::class, 'favorites']);
$router->get('/api/user/forum-history', [UserForum::class, 'history']);
$router->post('/api/user/forum-posts/{post_id}/reward', [UserForum::class, 'reward']);
$router->put('/api/user/forum-posts/{post_id}/paid-content', [UserForum::class, 'setPaidContent']);
$router->post('/api/user/forum-posts/{post_id}/paid-content/buy', [UserForum::class, 'buyPaidContent']);
$router->post('/api/user/forum-posts/{post_id}/sections', [UserForum::class, 'createSection']);
$router->put('/api/user/forum-posts/{post_id}/sections/reorder', [UserForum::class, 'reorderSections']);
$router->put('/api/user/forum-posts/{post_id}/sections/{section_id}', [UserForum::class, 'updateSection']);
$router->delete('/api/user/forum-posts/{post_id}/sections/{section_id}', [UserForum::class, 'deleteSection']);
$router->post('/api/user/forum-posts/{post_id}/sections/{section_id}/buy', [UserForum::class, 'buySection']);
$router->post('/api/user/forum-content/{target_type}/{target_id}/like', [UserForum::class, 'contentLike']);
$router->post('/api/user/forum-content/{target_type}/{target_id}/favorite', [UserForum::class, 'contentFavorite']);
$router->put('/api/user/forum-posts/{post_id}/comments/{comment_id}/pin', [UserForum::class, 'pinComment']);
$router->put('/api/user/forum-personal/{target_type}/{target_id}/position', [UserForum::class, 'personalPosition']);
$router->post('/api/user/forum-content/{target_type}/{target_id}/forward', [UserForum::class, 'forwardContent']);
$router->post('/api/user/reports', [UserForum::class, 'report']);
$router->get('/api/user/bounty-categories', [UserBounty::class, 'categories']);
$router->get('/api/user/bounty-category-requests', [UserBounty::class, 'categoryRequests']);
$router->post('/api/user/bounty-category-requests', [UserBounty::class, 'createCategoryRequest']);
$router->get('/api/user/bounties', [UserBounty::class, 'index']);
$router->post('/api/user/bounties', [UserBounty::class, 'create']);
$router->get('/api/user/bounties/{bounty_id}', [UserBounty::class, 'show']);
$router->post('/api/user/bounties/{bounty_id}/submissions', [UserBounty::class, 'submit']);
$router->post('/api/user/bounties/{bounty_id}/award', [UserBounty::class, 'award']);
$router->post('/api/user/bounties/{bounty_id}/cancel', [UserBounty::class, 'cancel']);
$router->post('/api/user/bounties/{bounty_id}/reactions', [UserBounty::class, 'reaction']);

// User private messaging, friends, chat rooms and customer service.
$router->post('/api/user/audio/transcriptions', [UserSpeech::class, 'transcribe']);
$router->get('/api/user/sticker-packs', [UserSticker::class, 'index']);
$router->post('/api/user/sticker-packs', [UserSticker::class, 'createPack']);
$router->put('/api/user/sticker-packs/{pack_id}', [UserSticker::class, 'updatePack']);
$router->delete('/api/user/sticker-packs/{pack_id}', [UserSticker::class, 'deletePack']);
$router->post('/api/user/sticker-packs/{pack_id}/stickers', [UserSticker::class, 'addSticker']);
$router->post('/api/user/sticker-packs/{pack_id}/stickers/batch', [UserSticker::class, 'batchAdd']);
$router->delete('/api/user/sticker-packs/{pack_id}/stickers/batch', [UserSticker::class, 'batchDelete']);
$router->delete('/api/user/sticker-packs/{pack_id}/stickers/{sticker_id}', [UserSticker::class, 'deleteSticker']);
$router->get('/api/user/cloud-sync/policy', [UserCloudSync::class, 'policy']);
$router->get('/api/user/cloud-sync/snapshots', [UserCloudSync::class, 'index']);
$router->post('/api/user/cloud-sync/snapshots', [UserCloudSync::class, 'create']);
$router->get('/api/user/cloud-sync/snapshots/{snapshot_id}', [UserCloudSync::class, 'show']);
$router->post('/api/user/cloud-sync/snapshots/{snapshot_id}/restore', [UserCloudSync::class, 'restore']);
$router->delete('/api/user/cloud-sync/snapshots/{snapshot_id}', [UserCloudSync::class, 'delete']);
$router->post('/api/user/chat-records/cleanup', [UserCloudSync::class, 'cleanupChat']);
$router->get('/api/user/messages/unread', [UserCommunication::class, 'unread']);
$router->post('/api/user/voice-calls', [UserVoiceCall::class, 'create']);
$router->get('/api/user/voice-calls/incoming', [UserVoiceCall::class, 'incoming']);
$router->get('/api/user/voice-calls/{call_id}', [UserVoiceCall::class, 'show']);
$router->post('/api/user/voice-calls/{call_id}/answer', [UserVoiceCall::class, 'answer']);
$router->post('/api/user/voice-calls/{call_id}/decline', [UserVoiceCall::class, 'decline']);
$router->post('/api/user/voice-calls/{call_id}/hangup', [UserVoiceCall::class, 'hangup']);
$router->post('/api/user/voice-calls/{call_id}/signals', [UserVoiceCall::class, 'signal']);
$router->get('/api/user/voice-calls/{call_id}/signals', [UserVoiceCall::class, 'signals']);
$router->get('/api/user/message-center', [UserCommunication::class, 'messageCenter']);
$router->put('/api/user/message-center/{target_type}/{target_id}/preference', [UserCommunication::class, 'saveConversationPreference']);
$router->get('/api/user/message-settings', [UserCommunication::class, 'messageSettings']);
$router->put('/api/user/message-settings', [UserCommunication::class, 'saveMessageSettings']);
$router->get('/api/user/messages/system', [UserCommunication::class, 'systemMessages']);
$router->post('/api/user/messages/private', [UserCommunication::class, 'privateMessage']);
$router->get('/api/user/conversations', [UserCommunication::class, 'conversations']);
$router->get('/api/user/conversations/{conversation_id}/messages', [UserCommunication::class, 'conversationMessages']);
$router->post('/api/user/messages/{message_id}/state', [UserCommunication::class, 'messageState']);
$router->post('/api/user/communication/{scope_type}/{target_id}/messages/{message_id}/state', [UserCommunication::class, 'communicationMessageState']);
$router->post('/api/user/messages/{message_id}/recall', [UserCommunication::class, 'recallMessage']);
$router->put('/api/user/messages/{message_id}', [UserCommunication::class, 'editMessage']);
$router->get('/api/user/messages/{message_id}/edits', [UserCommunication::class, 'messageEditHistory']);
$router->post('/api/user/message-forwards', [UserCommunication::class, 'forwardMessages']);
$router->get('/api/user/message-forwards/{forward_id}', [UserCommunication::class, 'forwardBundle']);
$router->get('/api/user/chat-search', [UserCommunication::class, 'searchMessages']);
$router->get('/api/user/chat-search/history', [UserCommunication::class, 'searchHistory']);
$router->delete('/api/user/chat-search/history', [UserCommunication::class, 'clearSearchHistory']);
$router->get('/api/user/messages/favorites', [UserCommunication::class, 'favoriteMessages']);
$router->get('/api/user/relationship-notices', [UserCommunication::class, 'relationshipNotices']);
$router->get('/api/user/drafts/{target_type}/{target_id}', [UserCommunication::class, 'draft']);
$router->put('/api/user/drafts/{target_type}/{target_id}', [UserCommunication::class, 'saveDraft']);
$router->delete('/api/user/drafts/{target_type}/{target_id}', [UserCommunication::class, 'deleteDraft']);
$router->get('/api/user/friends/requests', [UserCommunication::class, 'friendRequests']);
$router->post('/api/user/friends/requests', [UserCommunication::class, 'sendFriendRequest']);
$router->get('/api/user/friends/qr-code', [UserCommunication::class, 'friendQrCode']);
$router->post('/api/user/friends/scan-qr', [UserCommunication::class, 'scanFriendQr']);
$router->post('/api/user/friends/requests/{request_id}/accept', [UserCommunication::class, 'acceptFriendRequest']);
$router->post('/api/user/friends/requests/{request_id}/reject', [UserCommunication::class, 'rejectFriendRequest']);
$router->post('/api/user/friends/requests/{request_id}/ignore', [UserCommunication::class, 'ignoreFriendRequest']);
$router->get('/api/user/friends', [UserCommunication::class, 'friends']);
$router->get('/api/user/friend-groups', [UserCommunication::class, 'friendGroups']);
$router->post('/api/user/friend-groups', [UserCommunication::class, 'createFriendGroup']);
$router->put('/api/user/friend-groups/{group_id}', [UserCommunication::class, 'updateFriendGroup']);
$router->delete('/api/user/friend-groups/{group_id}', [UserCommunication::class, 'deleteFriendGroup']);
$router->put('/api/user/friends/{friend_user_id}', [UserCommunication::class, 'updateFriend']);
$router->delete('/api/user/friends/{friend_user_id}', [UserCommunication::class, 'deleteFriend']);
$router->get('/api/user/chat-room-groups', [UserGroup::class, 'userGroups']);
$router->post('/api/user/chat-room-groups', [UserGroup::class, 'createUserGroup']);
$router->put('/api/user/chat-room-groups/{group_id}', [UserGroup::class, 'updateUserGroup']);
$router->delete('/api/user/chat-room-groups/{group_id}', [UserGroup::class, 'deleteUserGroup']);
$router->get('/api/user/chat-rooms', [UserGroup::class, 'index']);
$router->post('/api/user/chat-rooms', [UserGroup::class, 'create']);
$router->post('/api/user/chat-rooms/scan-qr', [UserGroup::class, 'scanQr']);
$router->post('/api/user/chat-rooms/scan-qr/join', [UserGroup::class, 'joinQr']);
$router->get('/api/user/chat-rooms/dissolved', [UserGroup::class, 'dissolved']);
$router->get('/api/user/chat-rooms/{room_id}/qr-code', [UserGroup::class, 'qrCode']);
$router->get('/api/user/chat-rooms/{room_id}', [UserGroup::class, 'show']);
$router->put('/api/user/chat-rooms/{room_id}/user-settings', [UserGroup::class, 'saveUserSettings']);
$router->put('/api/user/chat-rooms/{room_id}', [UserGroup::class, 'update']);
$router->post('/api/user/chat-rooms/{room_id}/avatar', [UserGroup::class, 'avatar']);
$router->delete('/api/user/chat-rooms/{room_id}', [UserGroup::class, 'dissolve']);
$router->post('/api/user/chat-rooms/{room_id}/restore', [UserGroup::class, 'restore']);
$router->post('/api/user/chat-rooms/{room_id}/join', [UserGroup::class, 'join']);
$router->post('/api/user/chat-rooms/{room_id}/leave', [UserGroup::class, 'leave']);
$router->get('/api/user/chat-rooms/{room_id}/members', [UserGroup::class, 'members']);
$router->put('/api/user/chat-rooms/{room_id}/members/{user_id}', [UserGroup::class, 'updateMember']);
$router->put('/api/user/chat-rooms/{room_id}/members/{user_id}/mute', [UserGroup::class, 'muteMember']);
$router->delete('/api/user/chat-rooms/{room_id}/members/{user_id}', [UserGroup::class, 'removeMember']);
$router->post('/api/user/chat-rooms/{room_id}/transfer', [UserGroup::class, 'transfer']);
$router->post('/api/user/chat-rooms/{room_id}/invitations', [UserGroup::class, 'invite']);
$router->get('/api/user/chat-room-invitations', [UserGroup::class, 'invitations']);
$router->post('/api/user/chat-room-invitations/{invitation_id}/accept', [UserGroup::class, 'acceptInvitation']);
$router->post('/api/user/chat-room-invitations/{invitation_id}/reject', [UserGroup::class, 'rejectInvitation']);
$router->post('/api/user/chat-room-invitations/{invitation_id}/ignore', [UserGroup::class, 'ignoreInvitation']);
$router->get('/api/user/chat-rooms/{room_id}/join-requests', [UserGroup::class, 'joinRequests']);
$router->post('/api/user/chat-rooms/{room_id}/join-requests/{request_id}/approve', [UserGroup::class, 'approveJoinRequest']);
$router->post('/api/user/chat-rooms/{room_id}/join-requests/{request_id}/reject', [UserGroup::class, 'rejectJoinRequest']);
$router->post('/api/user/chat-rooms/{room_id}/join-requests/{request_id}/ignore', [UserGroup::class, 'ignoreJoinRequest']);
$router->get('/api/user/chat-rooms/{room_id}/messages', [UserGroup::class, 'messages']);
$router->post('/api/user/chat-rooms/{room_id}/messages', [UserGroup::class, 'sendMessage']);
$router->put('/api/user/chat-rooms/{room_id}/messages/{message_id}', [UserGroup::class, 'editMessage']);
$router->get('/api/user/chat-rooms/{room_id}/messages/{message_id}/edits', [UserGroup::class, 'messageEditHistory']);
$router->delete('/api/user/chat-rooms/{room_id}/messages/{message_id}', [UserGroup::class, 'deleteMessage']);
$router->post('/api/user/chat-rooms/{room_id}/read', [UserGroup::class, 'markRead']);
$router->get('/api/user/chat-rooms/{room_id}/files', [UserGroup::class, 'files']);
$router->post('/api/user/chat-rooms/{room_id}/files', [UserGroup::class, 'addFile']);
$router->post('/api/user/chat-rooms/{room_id}/files/{file_id}/download', [UserGroup::class, 'recordFileDownload']);
$router->delete('/api/user/chat-rooms/{room_id}/files/{file_id}', [UserGroup::class, 'deleteFile']);
$router->get('/api/user/chat-rooms/{room_id}/albums', [UserGroup::class, 'albums']);
$router->post('/api/user/chat-rooms/{room_id}/albums', [UserGroup::class, 'createAlbum']);
$router->delete('/api/user/chat-rooms/{room_id}/albums/{album_id}', [UserGroup::class, 'deleteAlbum']);
$router->post('/api/user/chat-rooms/{room_id}/albums/{album_id}/photos', [UserGroup::class, 'addPhoto']);
$router->delete('/api/user/chat-rooms/{room_id}/albums/{album_id}/photos/{photo_id}', [UserGroup::class, 'deletePhoto']);
$router->get('/api/user/chat-rooms/{room_id}/votes', [UserGroup::class, 'groupVotes']);
$router->post('/api/user/chat-rooms/{room_id}/votes', [UserGroup::class, 'createGroupVote']);
$router->get('/api/user/chat-rooms/{room_id}/votes/{vote_id}', [UserGroup::class, 'showGroupVote']);
$router->post('/api/user/chat-rooms/{room_id}/votes/{vote_id}/submit', [UserGroup::class, 'submitGroupVote']);
$router->post('/api/user/chat-rooms/{room_id}/votes/{vote_id}/close', [UserGroup::class, 'closeGroupVote']);
$router->delete('/api/user/chat-rooms/{room_id}/votes/{vote_id}', [UserGroup::class, 'deleteGroupVote']);
$router->get('/api/user/chat-rooms/{room_id}/solitaires', [UserGroup::class, 'solitaires']);
$router->post('/api/user/chat-rooms/{room_id}/solitaires', [UserGroup::class, 'createSolitaire']);
$router->get('/api/user/chat-rooms/{room_id}/solitaires/{solitaire_id}', [UserGroup::class, 'showSolitaire']);
$router->post('/api/user/chat-rooms/{room_id}/solitaires/{solitaire_id}/join', [UserGroup::class, 'joinSolitaire']);
$router->post('/api/user/chat-rooms/{room_id}/solitaires/{solitaire_id}/close', [UserGroup::class, 'closeSolitaire']);
$router->delete('/api/user/chat-rooms/{room_id}/solitaires/{solitaire_id}', [UserGroup::class, 'deleteSolitaire']);
$router->get('/api/user/service/session', [UserCommunication::class, 'serviceSession']);
$router->get('/api/user/service/messages', [UserCommunication::class, 'serviceMessages']);
$router->post('/api/user/service/messages', [UserCommunication::class, 'sendServiceMessage']);

// User cards, commerce and interactive activities.
$router->post('/api/user/cards/redeem', [UserCard::class, 'redeem']);
$router->get('/api/user/cards/redeem-logs', [UserCard::class, 'logs']);
$router->get('/api/user/orders', [UserShop::class, 'orders']);
$router->get('/api/user/orders/{order_source}/{order_id}', [UserShop::class, 'order']);
$router->post('/api/user/orders/{order_source}/{order_id}/cancel', [UserShop::class, 'cancelOrder']);
$router->post('/api/user/orders/{order_id}/cancel', [UserCommerce::class, 'cancelOrder']);
$router->get('/api/user/shop-categories', [UserShop::class, 'categories']);
$router->get('/api/user/shop-goods', [UserShop::class, 'goods']);
$router->get('/api/user/shop-goods/{goods_id}', [UserShop::class, 'showGoods']);
$router->post('/api/user/shop-goods/{goods_id}/buy', [UserShop::class, 'buy']);
$router->get('/api/user/shop-goods/{goods_id}/comments', [UserShop::class, 'comments']);
$router->post('/api/user/shop-goods/{goods_id}/comments', [UserShop::class, 'createComment']);
$router->put('/api/user/shop-comments/{comment_id}', [UserShop::class, 'updateComment']);
$router->delete('/api/user/shop-comments/{comment_id}', [UserShop::class, 'deleteComment']);
$router->post('/api/user/shop-comments/{comment_id}/reactions', [UserShop::class, 'commentReaction']);
$router->post('/api/user/shop-goods/{goods_id}/reactions', [UserShop::class, 'reaction']);
$router->post('/api/user/shop-goods/{goods_id}/forward', [UserShop::class, 'forward']);
$router->post('/api/user/shop-goods/{goods_id}/recommend', [UserShop::class, 'recommend']);
$router->get('/api/user/favorites/shop-goods', [UserShop::class, 'favorites']);
$router->get('/api/user/red-packets', [UserCommerce::class, 'redPackets']);
$router->post('/api/user/red-packets', [UserCommerce::class, 'createRedPacket']);
$router->get('/api/user/red-packets/{packet_id}', [UserCommerce::class, 'redPacketDetail']);
$router->post('/api/user/red-packets/{packet_id}/claim', [UserCommerce::class, 'claimRedPacket']);
$router->post('/api/user/red-packets/{packet_id}/refund', [UserCommerce::class, 'refundRedPacket']);
$router->get('/api/user/transfers', [UserCommerce::class, 'transfers']);
$router->post('/api/user/transfers', [UserCommerce::class, 'createTransfers']);
$router->get('/api/user/transfers/{transfer_id}', [UserCommerce::class, 'transferDetail']);
$router->post('/api/user/transfers/{transfer_id}/accept', [UserCommerce::class, 'acceptTransfer']);
$router->post('/api/user/transfers/{transfer_id}/refund', [UserCommerce::class, 'refundTransfer']);
$router->get('/api/user/gift-catalog', [UserCommerce::class, 'giftCatalog']);
$router->get('/api/user/gifts', [UserCommerce::class, 'gifts']);
$router->post('/api/user/gifts', [UserCommerce::class, 'createGifts']);
$router->get('/api/user/gifts/{gift_id}', [UserCommerce::class, 'giftDetail']);
$router->post('/api/user/gifts/{gift_id}/accept', [UserCommerce::class, 'acceptGift']);
$router->post('/api/user/gifts/{gift_id}/refund', [UserCommerce::class, 'refundGift']);
$router->get('/api/user/lottery-prizes', [UserCommerce::class, 'lotteryPrizes']);
$router->post('/api/user/lottery/draw', [UserCommerce::class, 'drawLottery']);
$router->get('/api/user/votes', [UserCommerce::class, 'votes']);
$router->post('/api/user/votes/{vote_id}/submit', [UserCommerce::class, 'submitVote']);
$router->get('/api/user/poll-categories', [UserPoll::class, 'categories']);
$router->post('/api/user/poll-categories', [UserPoll::class, 'createCategory']);
$router->put('/api/user/poll-categories/{category_id}', [UserPoll::class, 'updateCategory']);
$router->delete('/api/user/poll-categories/{category_id}', [UserPoll::class, 'deleteCategory']);
$router->get('/api/user/polls', [UserPoll::class, 'polls']);
$router->post('/api/user/polls', [UserPoll::class, 'createPoll']);
$router->get('/api/user/polls/{poll_id}', [UserPoll::class, 'show']);
$router->post('/api/user/polls/{poll_id}/vote', [UserPoll::class, 'vote']);
$router->post('/api/user/polls/{poll_id}/close', [UserPoll::class, 'close']);
$router->delete('/api/user/polls/{poll_id}', [UserPoll::class, 'delete']);

// User files, uploads, feedback and bot answers.
$router->get('/api/user/remote-files', [UserFileFeedback::class, 'files']);
$router->get('/api/user/remote-files/{file_id}', [UserFileFeedback::class, 'showFile']);
$router->get('/api/user/uploads', [UserFileFeedback::class, 'uploads']);
$router->post('/api/user/uploads', [UserFileFeedback::class, 'upload']);
$router->delete('/api/user/uploads/{upload_id}', [UserFileFeedback::class, 'deleteUpload']);
$router->post('/api/user/uploads/{upload_id}/favorite', [UserFileFeedback::class, 'favoriteUpload']);
$router->post('/api/user/feedbacks', [UserFileFeedback::class, 'createFeedback']);
$router->get('/api/user/feedbacks', [UserFileFeedback::class, 'feedbacks']);
$router->post('/api/user/bot/ask', [UserFileFeedback::class, 'botAsk']);
$router->get('/api/user/ai/conversations', [UserAiConversation::class, 'index']);
$router->get('/api/user/ai/conversations/{conversation_id}/messages', [UserAiConversation::class, 'messages']);
$router->delete('/api/user/ai/conversations/{conversation_id}', [UserAiConversation::class, 'delete']);

return $router;
